export enum APP_MODULES {
  USERS = 'USERS',
  HEADQUARTERS = 'HEADQUARTERS',
  USER_AREA = 'USER_AREA',
  USER_POSITION = 'USER_POSITION',
  USER_ROLES = 'USER_ROLES',
  TENANT = 'TENANT',
  FILES = 'FILES',
  NOTIFICATIONS = 'NOTIFICATIONS',
  SETTING = 'SETTING',
  MEMBERSHIP = 'MEMBERSHIP',
  IRP_ROAD_TAXES='IRP_ROAD_TAXES'

}


