export enum APP_MODULES {
  USERS = 'USERS',
  HEADQUARTERS = 'HEADQUARTERS',
  USER_AREA = 'USER_AREA',
  USER_POSITION = 'USER_POSITION',
  USER_ROLES = 'USER_ROLES',
  TENANT = 'TENANT',
  FILES = 'FILES',
  NOTIFICATIONS = 'NOTIFICATIONS',
  SETTING = 'SETTING',
  MEMBERSHIP = 'MEMBERSHIP',
  IRP_ROAD_TAXES='IRP_ROAD_TAXES',
  IFTA_FUEL_TAXES='IRP_ROAD_TAXES',
  DOT_INFO='DOT_INFO',
  SUBSTANCE_COMPLIANCE_CLEARING_HOUSE='SUBSTANCE_COMPLIANCE_CLEARING_HOUSE',
  DRIVER_FILES='DRIVER_FILES',
  ANNUAL_VEH_INSP_STATE_RERMITS='ANNUAL_VEH_INSP_STATE_RERMITS',
  TRAILER_RENTAL='TRAILER_RENTAL',
  YARD_RENTAL='TRAILER_RENTAL',
  FINANCED_EQUIPMENT='FINANCED_EQUIPMENT',
  ACCOUNTING='ACCOUNTING',
}


