export enum APP_MODULES {
  USERS = 'USERS',
  USER_AREA = 'USER_AREA',
  USER_POSITION = 'USER_POSITION',
  USER_ROLES = 'USER_ROLES',
  TENANT = 'TENANT',
  FILES = 'FILES',
  TRANSCODER = 'TRANSCODER',
  FFMPG_OPTION = 'FFMPG_OPTION',
  FFMPG_TEMPLATE = 'FFMPG_TEMPLATE',
}


